;;; leadkey-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from leadkey.el

(defvar leadkey-mode nil
"Non-nil if Leadkey mode is enabled.
See the `leadkey-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `leadkey-mode'.")
(custom-autoload 'leadkey-mode "leadkey" nil)
(autoload 'leadkey-mode "leadkey"
"Global minor mode for leader key support.

When enabled, leader keys defined in `leadkey-keys' are activated
in `key-translation-map'.

This is a global minor mode.  If called interactively, toggle the
`Leadkey mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='leadkey-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "leadkey" '("leadkey-"))


;;; Generated autoloads from leadkey-which-key.el

(autoload 'leadkey-which-key-setup "leadkey-which-key"
"Set up which-key integration hooks into leadkey.")
(register-definition-prefixes "leadkey-which-key" '("leadkey-which-key-"))

;;; End of scraped data

(provide 'leadkey-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; leadkey-autoloads.el ends here
